version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Pa88w0rd
      - MYSQL_DATABASE=db
      - REDIS_HOST=redis

  ui:
    build: 
      context: ./ui
      dockerfile: ./ui/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api

  proxy:
    build: 
      context: ./proxy
      dockerfile: ./proxy/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - ui

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Pa88w0rd
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
